### ISSUE TITLE
Attention Is All You Need

### ISSUE THREAD

**Issue by TeAmP0is0N** [osDFS/YouthIcon#14]
After completing the series of issues #9, #10, #11, #12, #13 you will have to continue with the non-RNN based models, you will implement the Transformer model from [Attention Is All You Need](https://arxiv.org/abs/1706.03762). This model will be based solely on attention mechanisms and introduces Multi-Head Attention. The encoder and decoder will be made of multiple layers, with each layer consisting of Multi-Head Attention and Positionwise Feedforward sublayers.

**Comment by simarpreetsingh-019** [comment]
I would like to work on this issue.

**Comment by kapilbindal** [comment]
Hey good work on previous issue. I except you to come up with even better results this time, so I am assigning this issue to you.
