### ISSUE TITLE
NLP with classification and vector  spaces: Perform sentiment analysis of tweets using logistic regression and then naïve Bayes  

### ISSUE THREAD

**Issue by TeAmP0is0N** [osDFS/YouthIcon#15]

**Comment by vikram7599** [comment]
Hi, I would like to work on this issue.

**Comment by kapilbindal** [comment]
Okay, So this issue is assigned to @vikram7599  now

**Comment by vikram7599** [comment]
Is there any specific dataset you guys want me to use?

**Comment by kapilbindal** [comment]
You can work on whatever you find best.

**Comment by kapilbindal** [comment]
@vikram7599 As you are not an SCI participant, then I can't assign this issue to you. You can coordinate with @TeAmP0is0N to work on this issue, till then I am retracting this issue from you.

**Comment by vikram7599** [comment]
Hi Kapil, I have messaged you on the osDFS slack channel, and given you the reason. Please assign this issue to me.

**Comment by ajaynair710** [comment]
I would like to work on this issue.

**Comment by simarpreetsingh-019** [comment]
I would Like to work on this issue, working on sentiment analysis by using Logistic regression.

**Comment by kapilbindal** [comment]
Hey @simarpreetsingh-019  as @ajaynair710 approached first, I'll be assigning this issue to him. You can check out other issues! We have many.
