### ISSUE TITLE
Seq2Seq model using pytorch

### ISSUE THREAD

**Issue by TeAmP0is0N** [osDFS/YouthIcon#6]
You have to create this PR under the tutorial section and I would suggest you avoid copying. You can add your code in `.py` or `.ipynb` extension. After adding the code you have to explain it that how did you approach. The structure can be like this:
Tutorial>Seq2Seq>Seq2Seq_using_pytorch.py
                  |
                  |> README.md

**Comment by TeAmP0is0N** [comment]
It will help you to know about the sequence to sequence learning with neural networks
https://arxiv.org/abs/1406.1078

**Comment by simarpreetsingh-019** [comment]
I would like to work on this issue, but will need some time because learning it from scratch

**Comment by kapilbindal** [comment]
@simarpreetsingh-019  I will be assigning you this issue but try to complete this in time.
